### ISSUE TITLE
small issues

### ISSUE THREAD

**Issue by mathieulagrange** [mathieulagrange/mathieulagrange.github.io#1]
tab name
tab logo ?
iframe does not work
title left justified
avatar round corner shaded

**Comment by MRossignol** [comment]
Image : ne pas la mettre directement dans le html, mais la mettre comme background d'une div
div.photo {
  background:url('images/photo.jpg')
}

**Comment by MRossignol** [comment]
Il va falloir ajuster la taille
CSS : background-size, background-position, background-repeat

**Comment by MRossignol** [comment]
Pour faire les angles arrondis
CSS : border-radius

**Comment by MRossignol** [comment]
Pour effet "volume"
DIV avec positionnement absolu exactement au-dessus de la div contenant la photo
Sur cette div, background: gradient

**Comment by MRossignol** [comment]
http://www.colorzilla.com/gradient-editor/

**Comment by MRossignol** [comment]
https://css-tricks.com/snippets/css/css-box-shadow/

**Comment by MRossignol** [comment]
https://en.wikipedia.org/wiki/Favicon

**Comment by MRossignol** [comment]
CSS : min-width et min-height

**Comment by MRossignol** [comment]
Gimp : layer -> transparency -> add alpha channel
